/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Conversation: () => import('#controllers/conversation_controller'),
  Message: () => import('#controllers/message_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notification: () => import('#controllers/notification_controller'),
  Presence: () => import('#controllers/presence_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Realtime: () => import('#controllers/realtime_controller'),
  Search: () => import('#controllers/search_controller'),
  Upload: () => import('#controllers/upload_controller'),
}
